name: DevelopmentBuild

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  buildForMainBranch:
    if: github.ref == 'refs/heads/main' # Ensure the workflow is run for the main branch
    name: main branch build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: [StandaloneWindows64, Android]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildOptions: DevelopmentBuild # Annotate as a development build
      - uses: actions/upload-artifact@v3
        with:
          name: build-dev-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  buildForWebGL:
    if: github.ref == 'refs/heads/webgl' # Ensure the workflow is run for the webgl branch
    name: webgl branch build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildOptions: DevelopmentBuild # Annotate as a development build
      - uses: actions/upload-artifact@v3
        with:
          name: build-dev-WebGL
          path: build/WebGL
